Feature: 103-Create features for Versioning project
  In order to check if the new node is published and the Version field is set to Defined
  As a various different roles
  I need to be able login and set min Version of the new node = max Version of the old node.

  @javascript @insulated
  Scenario: Authenticated User as admin, raptor admin and raptor editor role
    Given I am on "/"
    Then I log on as "admin"
    Then I should be redirected to "users/admin"
    Then I click "Add content"
    Then I should be redirected to "node/add/raptor-article"
    Then I fill in "title" as "Min Version equal Max Version old node"
    Then I select "1.3.6" from "Min Version"
    Then I select "2.5.4" from "Max Version"
    Then I select "Raptor" from "Platform"
    Then I press button "Save"
    Then I click "Content summary"
    Then I should be redirected to "content-summary"
    Then I click "Min Version equal Max Version old node"
    Then I should be redirected to "raptor/article/min-version-equal-max-version-old-node"
    Then I click "Clone this raptor article"
    Then I should be redirected to "node/38/clone/confirm"
    Then I select "100210300" from "Min Version"
    Then I select "200500400" from "Max Version"
    Then I press button "Save"
    Then I should be redirected to "content-summary"
    Then I click "Min Version equal Max Version old node"
    Then I should be redirected to "raptor/article/min-version-equal-max-version-old-node"
    Then I should see "Max Version: "
    Then I click "Log out"
    Then I fill in "username" as "raptor.editor"
    Then I fill in password "password" as "1234"
    Then I press button "Log in"
    Then I should be redirected to "users/raptoreditor"
    Then I should be redirected to "content-summary"
    Then I click "Clone of Min Version equal Max Version old node"
    Then I should be redirected to "raptor/article/clone-min-version-equal-max-version-old-node"
    Then I select "100210300" from "Min Version"
    Then I select "200500400" from "Max Version"
    Then I press button "Save"
    Then I should be redirected to "content-summary"
    Then I click "Min Version equal Max Version old node"
    Then I should be redirected to "raptor/article/min-version-equal-max-version-old-node"
    Then I should see "Max Version: "
    Then I click "Log out"
    Then I fill in "username" as "raptor.admin"
    Then I fill in password "password" as "1234"
    Then I press button "Log in"
    Then I should be redirected to "users/raptoradmin"
    Then I should be redirected to "content-summary"
    Then I click "Clone of Min Version equal Max Version old node"
    Then I should be redirected to "raptor/article/clone-min-version-equal-max-version-old-node"
    Then I select "100210300" from "Min Version"
    Then I select "200500400" from "Max Version"
    Then I press button "Save"
    Then I should be redirected to "content-summary"
    Then I click "Min Version equal Max Version old node"
    Then I should be redirected to "raptor/article/min-version-equal-max-version-old-node"
    Then I should see "Max Version: "
    Then I click "Edit"
    Then I press button "Delete"
    Then I press button "Delete"
    Then I click "Log out"
    
   
