Feature: 104-Create features for Versioning project
  In order to show titles of all nodes that have the same Base Article field as the node we are viewing
  As a various different roles
  I need to be able login and check not show the node that we are viewing in this list.

  @javascript @insulated
  Scenario: Authenticated User as admin, raptor admin and raptor editor role
    Given I am on "/"
    Then I log on as "admin"
    Then I should be redirected to "users/admin"
    Then I click "Add content"
    Then I should be redirected to "node/add/raptor-article"
    Then I fill in "title" as "Base Article pointing to self"
    Then I select "1.3.6" from "Min Version"
    Then I select "2.5.4" from "Max Version"
    Then I select "Raptor" from "Platform"
    Then I press button "Save"
    Then I click "Content summary"
    Then I should be redirected to "content-summary"
    Then I click "Base Article pointing to self"
    Then I should be redirected to "raptor/article/base-article-pointing-self"
    Then I click "Clone this raptor article"
    Then I should be redirected to "node/38/clone/confirm"
    Then I fill in "edit-field-base-article-und" as "Base Article pointing to self"
    Then I press button "Save"
    Then I click "Content summary"
    Then I should be redirected to "content-summary"
    Then I click "Base Article pointing to self"
    Then I should be redirected to "raptor/article/base-article-pointing-self"
    Then I should see "Raptor Articles"
    Then I click "Log out"
    Then I fill in "username" as "raptor.editor"
    Then I fill in password "password" as "1234"
    Then I press button "Log in"
    Then I should be redirected to "users/raptoreditor"
    Then I should be redirected to "content-summary"
    Then I click "Base Article pointing to self"
    Then I should be redirected to "raptor/article/base-article-pointing-self"
    Then I click "Clone this raptor article"
    Then I should be redirected to "node/38/clone/confirm"
    Then I fill in "edit-field-base-article-und" as "Base Article pointing to self"
    Then I press button "Save"
    Then I click "Content summary"
    Then I should be redirected to "content-summary"
    Then I click "Base Article pointing to self"
    Then I should be redirected to "raptor/article/base-article-pointing-self"
    Then I should see "Raptor Articles"
    Then I click "Log out"
    Then I fill in "username" as "raptor.admin"
    Then I fill in password "password" as "1234"
    Then I press button "Log in"
    Then I should be redirected to "users/raptoradmin"
    Then I should be redirected to "content-summary"
    Then I click "Base Article pointing to self"
    Then I should be redirected to "raptor/article/base-article-pointing-self"
    Then I click "Clone this raptor article"
    Then I should be redirected to "node/38/clone/confirm"
    Then I fill in "edit-field-base-article-und" as "Base Article pointing to self"
    Then I press button "Save"
    Then I click "Content summary"
    Then I should be redirected to "content-summary"
    Then I click "Base Article pointing to self"
    Then I should be redirected to "raptor/article/base-article-pointing-self"
    Then I should see "Raptor Articles"
    Then I click "Edit"
    Then I press button "Delete"
    Then I press button "Delete"
    Then I click "Log out"
    Then I click "Log out"

   
