Feature: PW-379 Email Confirmation of Mashup Update to Mashup Owner
If a mashup is updated by an owner, a confirmation message goes to the owner's email address.
As an admin
I need to check if an owner receives an email after udpating the mashup

  @javascript @insulated @379
  Scenario: Login
    Then I log on as "vishaltest"
    Given I am on "/add/mashup"
    When I fill in "Mashup Name" with "test mashup content3"
    When I fill in "URL" with "http://www.example.com"
    When I fill in "edit-field-api-und-0-target-id" with "Flickr"
    And I select "Backend" from "Primary Category"
    When I fill in "edit-body-und-0-value" with "test content"
    And I attach the file "download.png" to "edit-field-mashup-image-und-0-upload"
    Then I press button "Save"
    Then I should be redirected to "mashup/test-mashup-content3"
    Then I click "Logout"
    Then I log on as "admin"
    Given I am on "mashup/test-mashup-content3"
    Then I click "Workflow"
    Then I check "edit-workflow-18"
    Then I press button "edit-submit"
    Then I check "edit-workflow-19"
    Then I press button "edit-submit"
    Then I click "Logout"
    Then I log on as "vishaltest"
    Given I am on "mashup/test-mashup-content3"
    Then I click "Edit"
    When I fill in "edit-body-und-0-value" with "test content new"
    Then I press button "Save"
    Then I click "Logout"
    Then I log on as "admin"
    Then I click "Reports"
    Then I click "Recent log messages"
    Then I should see "Successfully sent email to xxvishal.khialani@gmail.comzz"
    Given I am on "mashup/test-mashup-content3"
    And I click "Edit"
    Then I press button "Delete"
    And I press button "Delete"
    Then I should see "deleted"
