Feature: PW-99 Update Eventlog on API publication
  Whenever a new API is published in the system, a new entry is inserted into eventlog.
  As a website manager
  I need to see if it really creates an entry in eventlog while publishing an API.


  @javascript @insulated @99
  Scenario: Login
    Then I log on as "vishaltest"
    Given I am on "/add/api"
    When I fill in "API Name" with "test api2"
    When I fill in "API Provider" with "test provider"
    Then I fill in "edit-field-api-home-page-und-0-url" with "http://www.google.com"
    When I fill in "API Endpoint" with "test endpoint"
    And I select "API Overviews" from "Primary category"
    And I select "Adobe" from "Secondary Categories"
    And I fill in "API Description" with "test api desc"
    Then I fill in "Related to?" with "text here!"
    Then I fill in "Other options" with "other options here"
    Then I press button "edit-submit"
    Then I should be redirected to "/api/test-api2"
    Then I should see "created"
    Then I click "Logout"
    Then I log on as "manager"
    Given I am on "/api/test-api2"
    And I click "Edit"
    Then I check "edit-workflow-12"
    When I fill in "Actual API Provider" with "Accenture"
    When I fill in "Changelog" with "changed to pending"
    Then I press button "edit-submit"
    Then I press button "edit-submit"
    Given I am on "/api/test-api2"
    And I click "Edit"
    Then I check "edit-workflow-13"
    When I fill in "Changelog" with "draft"
    Then I press button "edit-submit"
    Given I am on "/api/test-api2"
    And I click "Edit"
    Then I check "edit-workflow-14"
    When I fill in "Changelog" with "published"
    Then I press button "edit-submit"
    Then I click "Logout"
    Then I log on as "admin"
    Given I am on "/eventlog"
    Then I should see "submitted API"
    Then I should see "published api"
    Then I should see "test api2"
    Given I am on "/api/test-api2"
    Then I click "Edit"
    And I press button "Delete"
    And I press button "Delete"
    Then I should see "deleted"
